### ISSUE TITLE
A cross-domain exception occurred while loading the map. 

### ISSUE THREAD

**Issue by Vhhhhh** [hnrchrdl/leaflet-tilelayer-colorizr#3]
Here is the code:
```
    L.tileLayer.colorizr("http://192.168.0.105:9090/img/{z}/{x}/{y}.png", {
        maxZoom: 18,
        minZoom: 3,
        colorize: function (pixel) {
            pixel.r = pixel.r + 100 - 26;
            pixel.g = pixel.g + 100 - 34;
            pixel.b = pixel.b + 100 - 150;
            return pixel;
        }
    }).addTo(map);
```
Set the following properties to false to solve the cross-domain, but there is a problem that can not adjust the color of the map, I hope to get your help as soon as possible.
![image](https://user-images.githubusercontent.com/40897141/81758633-fc0f1780-94f4-11ea-87b3-57932a845b60.png)
![image](https://user-images.githubusercontent.com/40897141/81758670-10531480-94f5-11ea-9cfa-3714c30ebda7.png)
Exception information: Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

**Comment by hnrchrdl** [comment]
I think this is most likely not an issue with this package, but with the tile server not sending CORS headers.

**Comment by Vhhhhh** [comment]
> I think this is most likely not an issue with this package, but with the tile server not sending CORS headers.


The problem has been solved, the reason is that the browser restricts the canvas to handle cross-domain pictures, thank you friends.
